### ISSUE TITLE
nevie bootovat ak je viac ako jeden hard disk

### ISSUE THREAD

**Issue by japdlsd** [koniiiik/oi-live#1]
pocas bootu hlada oi-live image spomedzi /dev/sdb1 az /dev/sdb8. Ale ked je vaicero hard diskov, tak USBcko dostane inu adresu (/dev/sdcX, /dev/sddX, …).

Riesenie: skusat postupne vsetky aj dalsie pismena :) Alebo aj nieco menej farmarske.

**Comment by koniiiik** [comment]
Heh, to mi trvalo, rok a skoro mesiac. Ale anyway, blbosť. Keď sa pozrieš na https://github.com/koniiiik/oi-live/blob/master/oi-live/hooks/oi-live#L43, zistíš, že on skúša všetky písmenká a potom jednu alebo dve číslice. A som si celkom istý, že počas tých rokov, čo som to používal, mi to vedelo naštartovať aj z USB kľúča na sdc1 alebo sdd1.

Akurát keď nájde niečo, čo vyzerá ako správny súbor, tak prestane hľadať ďalej.

Problém bude niekde inde, napríklad, že sa ti USB kľúč inicializuje príliš neskoro. Z nejakého dôvodu – asi kvôli buggy USB kľúčom – modul `usb_storage` čaká by default päť sekúnd, kým inicializuje device. Toto sa overriduje boot parametrom `usb-storage.delay_use=0`, ktorý zníži delay na nulu, teda sa inicializuje hneď, a tento parameter je by default v syslinuxovej konfigurácii.
